/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class BookFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightJPanel
     */
   
    private JPanel UserProcessContainer;
    private Airliner airliner;
    private TravelAgency travelagency;
    BookFlightJPanel(JPanel UserProcessContainer, Airliner airliner) {
         initComponents();
         this.UserProcessContainer = UserProcessContainer;
         this.airliner = airliner;
         travelagency=new TravelAgency();
         
       txtAirlinerName.setText(airliner.getAirlinername());
       
      for (Flight flight :airliner.getFlightList() ){
        txtFlightNumber.setText(flight.getFlightnumber());
        txtFlightFrom.setText(flight.getFrom());
        txtFlightTo.setText(flight.getTo());
        txtFlightDeparture.setText(flight.getDeparturetime());
        txtFlightArrival.setText(flight.getArrivaltime());
        txtFlightPrice.setText(flight.getFlightprice());
        
      }  
    }
    
   
            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtFlightNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFlightFrom = new javax.swing.JTextField();
        txtFlightTo = new javax.swing.JTextField();
        txtFlightDeparture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFlightArrival = new javax.swing.JTextField();
        btnBookFlight = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCustomerContact = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtFlightPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK FLIGHT FOR CUSTOMER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        txtAirlinerName.setEditable(false);
        txtAirlinerName.setEnabled(false);
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 230, 40));

        txtFlightNumber.setEditable(false);
        txtFlightNumber.setEnabled(false);
        add(txtFlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 230, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Airliner Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Flight Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 180, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("From:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("To:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 30));

        txtFlightFrom.setEditable(false);
        txtFlightFrom.setEnabled(false);
        add(txtFlightFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 230, 40));

        txtFlightTo.setEditable(false);
        txtFlightTo.setEnabled(false);
        add(txtFlightTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, 40));

        txtFlightDeparture.setEditable(false);
        txtFlightDeparture.setEnabled(false);
        add(txtFlightDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Departure Date and Time:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Price");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 30));

        txtFlightArrival.setEditable(false);
        txtFlightArrival.setEnabled(false);
        add(txtFlightArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 230, 40));

        btnBookFlight.setText("BOOK FLIGHT");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });
        add(btnBookFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 230, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CUSTOMER DETAILS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CUSTOMER CONTACT");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 200, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CUSTOMER NAME");
        jLabel10.setToolTipText("");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 30));
        add(txtCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 230, 40));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 230, 40));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        txtFlightPrice.setEditable(false);
        txtFlightPrice.setEnabled(false);
        add(txtFlightPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 230, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Arrival Date and Time:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        String customername = txtCustomerName.getText();
        String customercontact = txtCustomerContact.getText();
        
        String airlinername = txtAirlinerName.getText();
        String flightno = txtFlightNumber.getText();
        String flightfrom = txtFlightFrom.getText();
        String flightto=txtFlightTo.getText();
        String flightdeparture = txtFlightDeparture.getText();
        String flightarrival = txtFlightArrival.getText();
        String flightprice = txtFlightPrice.getText();
      
        JOptionPane.showMessageDialog(null,"SEAT BOOKED SUCCESSFULLY");

        
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtFlightArrival;
    private javax.swing.JTextField txtFlightDeparture;
    private javax.swing.JTextField txtFlightFrom;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtFlightPrice;
    private javax.swing.JTextField txtFlightTo;
    // End of variables declaration//GEN-END:variables
}
