/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Airliner;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageJPanel
     */
    private JPanel UserProcessContainer;
    private TravelAgency travelagency;
    ManageJPanel(JPanel UserProcessContainer, TravelAgency travelagency) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.travelagency = travelagency;
        populateTable3();
        
    }
     public void populateTable3() {
    DefaultTableModel dtm = (DefaultTableModel)tblflight12.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner:travelagency.getAirlinerdirectory().getAirlinerList()) {
            int i=0;
            for(Flight flight:airliner.getFlightList()) {
            
            Object[] row = new Object[7];
            row[0]=airliner;
           // row[1]=airliner.getFlightList().get(i).getFlightnumber();
           row[1]=flight.getFlightnumber(); 
           row[2]=airliner.getFlightList().get(i).getFrom();
            row[3]=airliner.getFlightList().get(i).getTo();
            row[4]=airliner.getFlightList().get(i).getDeparturetime();
            row[5]=airliner.getFlightList().get(i).getArrivaltime();
            row[6]=airliner.getFlightList().get(i).getFlightprice();
            dtm.addRow(row);
            i++;
                    }
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblflight12 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSelectandBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtmin = new javax.swing.JTextField();
        txtmax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblflight12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight Number", "From", "To", "Source", "Destination", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblflight12);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 650, 270));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Source:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Destination :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, 50));

        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 170, 50));
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 170, 50));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 170, 50));

        btnSelectandBook.setText("SELECT AND BOOK");
        btnSelectandBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectandBookActionPerformed(evt);
            }
        });
        add(btnSelectandBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, 170, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("BEST FLIGHT DEALS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));

        jLabel4.setText("Min:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 50, 40));
        add(txtmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 60, 50));

        txtmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaxActionPerformed(evt);
            }
        });
        add(txtmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 60, 50));

        jLabel5.setText("Price :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 40));

        jLabel6.setText("Max:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         if((txtSource.getText() != null)&& !(txtSource.getText().isEmpty())
           && (txtDestination.getText() != null)&& !(txtDestination.getText().isEmpty()) 
           && (txtmin.getText() != null)&& !(txtmin.getText().isEmpty())
           && (txtmax.getText() != null)&& !(txtmax.getText().isEmpty()) 
            )
       {
           
       try{
        
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        int minprice =Integer.parseInt(txtmin.getText());
        int maxprice = Integer.parseInt(txtmax.getText());
        Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtSource.getText() + txtDestination.getText() + txtmin.getText() +txtmax.getText());
            boolean boo = m.find();
        if(boo == true || source == null || destination == null || minprice == 0 ||  maxprice == 0) {
            JOptionPane.showMessageDialog(null,"Please remove special character from text field");
        }
        else{
         DefaultTableModel dtm = (DefaultTableModel)tblflight12.getModel();
         dtm.setRowCount(0);
        for(Airliner airliner: travelagency.getAirlinerdirectory().getAirlinerList()) {
            for(Flight flight:airliner.getFlightList()) {
                int price = Integer.parseInt(flight.getFlightprice());
                if(flight.getFrom().equals(source)&&flight.getTo().equals(destination)){
                    if((price>minprice)&&(price<maxprice))
                    {
                    Object[] row = new Object[7];
                    row[0]=airliner;
                    row[1]=flight.getFlightnumber();
                    row[2]=flight.getFrom();
                    row[3]=flight.getTo();
                    row[4]=flight.getDeparturetime();
                    row[5]=flight.getArrivaltime();
                    row[6]=flight.getFlightprice();
                    System.out.println(row[1]+"/t"+row[2]);
                    dtm.addRow(row);
                    }
                }
            }
        }
        }}catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Values ");
        }
       }
      else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSelectandBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectandBookActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblflight12.getSelectedRow();
         System.out.println("hi");
         if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);

         }
         else {
             System.out.println("2");
           Airliner airliner = (Airliner)tblflight12.getValueAt(selectedRow,0);
            System.out.println("3");
          // System.out.println("FLIGHT DETAILS"+ airliner);
         BookFlightJPanel panel = new BookFlightJPanel(UserProcessContainer,airliner);
        UserProcessContainer.add("BookFlightJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer); 
         }
           
        
    }//GEN-LAST:event_btnSelectandBookActionPerformed

    private void txtmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectandBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblflight12;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtmax;
    private javax.swing.JTextField txtmin;
    // End of variables declaration//GEN-END:variables
}
