/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.TravelAgency;
import UserInterface.ManageTravelAgency.TravelAgencyMngWorkAreaJPanel;
import UserInterface.ManageAirlines.MngAirlinerWorkArea;
import UserInterface.ManageCustomers.CustomersMngWorkAreaJPanel;
import java.awt.CardLayout;

/**
 *
 * @author rishabhjain
 */
public class TravelAgencyMainJFrame extends javax.swing.JFrame {

    private TravelAgency travelagency;
   // private AirlinerDirectory airlinerdirectory;
    /**
     * Creates new form TravelAgencyMain
     */
    public TravelAgencyMainJFrame() {
        initComponents();
        this.travelagency = new TravelAgency();
     //   ad = travelagency.getAirlinerdirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        UserProcessContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomers = new javax.swing.JButton();
        btnAirliners = new javax.swing.JButton();
        btnTravelagency = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        UserProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(UserProcessContainer);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        jPanel2.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 259, 190, 40));

        btnAirliners.setText("Airliners");
        btnAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinersActionPerformed(evt);
            }
        });
        jPanel2.add(btnAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 40));

        btnTravelagency.setText("Travel Agency");
        btnTravelagency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelagencyActionPerformed(evt);
            }
        });
        jPanel2.add(btnTravelagency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 190, 40));

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelagencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelagencyActionPerformed
        // TODO add your handling code here:
        TravelAgencyMngWorkAreaJPanel panel = new TravelAgencyMngWorkAreaJPanel(UserProcessContainer,travelagency);
        UserProcessContainer.add("MngTravelAgencyWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
        



    }//GEN-LAST:event_btnTravelagencyActionPerformed

    private void btnAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinersActionPerformed
        // TODO add your handling code here:
        // AirlinerDirectory ad = travelagency.getAirlinerdirectory();
        MngAirlinerWorkArea panel = new MngAirlinerWorkArea(UserProcessContainer,travelagency);
        UserProcessContainer.add("MngAirlinerWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
        
    }//GEN-LAST:event_btnAirlinersActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        CustomersMngWorkAreaJPanel panel = new CustomersMngWorkAreaJPanel(UserProcessContainer,travelagency);
        UserProcessContainer.add("MngCustomerWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserProcessContainer;
    private javax.swing.JButton btnAirliners;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnTravelagency;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
