/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class CreateNewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewFlightJPanel
     */
    private JPanel UserProcessContainer;
    private Airliner airliner;
    CreateNewFlightJPanel(JPanel UserProcessContainer, Airliner airliner) {
             initComponents();
             this.UserProcessContainer = UserProcessContainer;
             this.airliner = airliner;
              txtAirlinerName.setText(airliner.getAirlinername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtFlightNumber = new javax.swing.JTextField();
        txtFlightTo = new javax.swing.JTextField();
        btnCreateFlight = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFlightArrival = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFlightDeparture = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFlightFrom = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE FLIGHT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 30));

        txtAirlinerName.setEditable(false);
        txtAirlinerName.setEnabled(false);
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, 40));
        add(txtFlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 40));
        add(txtFlightTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 230, 40));

        btnCreateFlight.setText("CREATE");
        btnCreateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFlightActionPerformed(evt);
            }
        });
        add(btnCreateFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 230, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("To:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Flight Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Airliner Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 180, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Price Of Seat :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 180, 30));
        add(txtFlightArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Departure Date and Time:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 180, 30));
        add(txtFlightDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 230, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("From:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 30));
        add(txtFlightFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, 40));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Arrival Date and Time:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 30));
        add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFlightActionPerformed
        // TODO add your handling code here:
        if((txtFlightNumber.getText() != null)&& !(txtFlightNumber.getText().isEmpty())
           && (txtFlightFrom.getText() != null)&& !(txtFlightFrom.getText().isEmpty()) 
           && (txtFlightTo.getText() != null)&& !(txtFlightTo.getText().isEmpty()) 
           && (txtFlightDeparture.getText() != null)&& !(txtFlightDeparture.getText().isEmpty()) 
           && (txtFlightArrival.getText() != null)&& !(txtFlightArrival.getText().isEmpty())
           && (txtprice.getText() != null)&& !(txtprice.getText().isEmpty())     
            )  
        {
        try {    
        
       
        String airlinername = txtAirlinerName.getText();
        String flightnumber = txtFlightNumber.getText();
        String from = txtFlightFrom.getText();
        String to = txtFlightTo.getText();
        String departuretime = txtFlightDeparture.getText();
        String arrivaltime = txtFlightArrival.getText();
        String price = txtprice.getText();
        
            Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtFlightNumber.getText() + txtFlightFrom.getText() + txtFlightTo.getText() + txtFlightDeparture.getText() + txtFlightArrival.getText() + txtprice.getText() );
            boolean boo = m.find();
            if(boo == true || flightnumber == null || from == null || to == null ||departuretime == null || arrivaltime == null || price == null) {
            JOptionPane.showMessageDialog(null,"Please remove special character from text field");
        }
         else{
            Flight flight= airliner.addFlight();
            flight.setFlightnumber(flightnumber);
            flight.setFrom(from);
            flight.setTo(to);
            flight.setDeparturetime(departuretime);
            flight.setArrivaltime(arrivaltime);
            flight.setFlightprice(price);
            JOptionPane.showMessageDialog(null,"Flight successfully created");
            }
        }catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Values ");
        }
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }
         
    }//GEN-LAST:event_btnCreateFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtFlightArrival;
    private javax.swing.JTextField txtFlightDeparture;
    private javax.swing.JTextField txtFlightFrom;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtFlightTo;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
