/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class CreateAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerJPanel
     */
    private JPanel UserProcessContainer;
    private AirlinerDirectory airlinerdirectory;

    CreateAirlinerJPanel(JPanel UserProcessContainer, AirlinerDirectory airlinerdirectory) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.airlinerdirectory = airlinerdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtAirlinerAddress = new javax.swing.JTextField();
        txtNoofAircrafts = new javax.swing.JTextField();
        btnCreateAirliner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 30));
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, 40));
        add(txtAirlinerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 40));
        add(txtNoofAircrafts, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, 40));

        btnCreateAirliner.setText("CREATE AIRLINER");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });
        add(btnCreateAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 230, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Number of Aircrafts:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Airliner Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Airliner Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 180, 30));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        if((txtAirlinerName.getText() != null)&& !(txtAirlinerName.getText().isEmpty())
           && (txtAirlinerAddress.getText() != null)&& !(txtAirlinerAddress.getText().isEmpty()) 
           && (txtNoofAircrafts.getText() != null)&& !(txtNoofAircrafts.getText().isEmpty()) 
            )
        {
            
          try {
            String airlinername = txtAirlinerName.getText();
            String airlineraddress = txtAirlinerAddress.getText();
            String airlinernoofaircrafts = txtNoofAircrafts.getText();
            
            Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtAirlinerName.getText() + txtAirlinerAddress.getText() + txtNoofAircrafts.getText() );
            boolean boo = m.find();
            if(boo == true || airlinername == null || airlineraddress == null || airlinernoofaircrafts == null) {
            JOptionPane.showMessageDialog(null,"Please remove special character from text field");
        }
            else{
            Airliner airliner = airlinerdirectory.addAirliner();
            airliner.setAirlinername(airlinername);
            airliner.setAirlineraddress(airlineraddress);
            airliner.setNoofairlines(airlinernoofaircrafts);
            //System.out.println("HI");
            JOptionPane.showMessageDialog(null,"Airliner successfully created");
            }
          }catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Values ");
        }
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }
        
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       UserProcessContainer .remove(this);
       Component[] componentArray = UserProcessContainer.getComponents();
       Component component = componentArray[componentArray.length-1];
       MngAirlinerWorkArea manageairlinerworkarea = (MngAirlinerWorkArea) component;
       manageairlinerworkarea.populateTable();
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAirlinerAddress;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtNoofAircrafts;
    // End of variables declaration//GEN-END:variables
}
