/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class ManageFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightJPanel
     */
   private JPanel UserProcessContainer;
   private Airliner airliner;
    ManageFlightJPanel(JPanel UserProcessContainer, Airliner airliner) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.airliner = airliner;
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateNewFlights = new javax.swing.JButton();
        btnViewFlights = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE FLIGHTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 30));

        btnCreateNewFlights.setText("CREATE NEW FLIGHTS");
        btnCreateNewFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewFlightsActionPerformed(evt);
            }
        });
        add(btnCreateNewFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, 50));

        btnViewFlights.setText("VIEW FLIGHTS");
        btnViewFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightsActionPerformed(evt);
            }
        });
        add(btnViewFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 260, 50));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightsActionPerformed
        // TODO add your handling code here:
        ViewFlightJPanel panel = new ViewFlightJPanel(UserProcessContainer,airliner);
        UserProcessContainer.add("ViewFlightJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer); 
    }//GEN-LAST:event_btnViewFlightsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateNewFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewFlightsActionPerformed
        // TODO add your handling code here:
        CreateNewFlightJPanel panel = new CreateNewFlightJPanel(UserProcessContainer,airliner);
        UserProcessContainer.add("CreateAirlinerJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer); 
    }//GEN-LAST:event_btnCreateNewFlightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewFlights;
    private javax.swing.JButton btnViewFlights;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
