/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class MngAirlinerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerJPanel
     */
    private JPanel UserProcessContainer;
    private TravelAgency travelagency;
    public MngAirlinerWorkArea(JPanel UserProcessContainer, TravelAgency travelagency) {
          initComponents();
          this.UserProcessContainer = UserProcessContainer; 
          this.travelagency=travelagency;
          populateTable();
    }
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) tblmanageairliners.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner: travelagency.getAirlinerdirectory().getAirlinerList()) {
            Object[] row = new Object[4];
            row[0]=airliner;
            row[1]=airliner.getAirlineraddress();
            row[2]=airliner.getNoofairlines();
            
            dtm.addRow(row);
        }
    }
    /**
     *
     */

 
  /*  public void populateTable2(){
         DefaultTableModel dtm = (DefaultTableModel) tblsearchairliners.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner: airlinerdirectory.getAirlinerList()) {
            Object[] row = new Object[4];
            row[0]=airliner;
            row[1]=airliner.getAirlineraddress();
            row[2]=airliner.getNoofairlines();
            System.out.println(row[2]);
            dtm.addRow(row);
        }
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmanageairliners = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtsearchairlines = new javax.swing.JTextField();
        btnSearchAirliner = new javax.swing.JButton();
        btnUpdateAirliner = new javax.swing.JButton();
        btnCreateAirliner = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsearchairliners = new javax.swing.JTable();
        btnManageFlights = new javax.swing.JButton();
        btnDeleteAirliner = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE AIRLINERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 6, 243, 38));

        tblmanageairliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airliner Name", "Airliner Address", "Number of Aircrafts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblmanageairliners);
        if (tblmanageairliners.getColumnModel().getColumnCount() > 0) {
            tblmanageairliners.getColumnModel().getColumn(0).setResizable(false);
            tblmanageairliners.getColumnModel().getColumn(1).setResizable(false);
            tblmanageairliners.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 600, 150));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Enter Airliner Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 40));
        add(txtsearchairlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 240, 40));

        btnSearchAirliner.setText("Search");
        btnSearchAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAirlinerActionPerformed(evt);
            }
        });
        add(btnSearchAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 140, 40));

        btnUpdateAirliner.setText("Update Airliner");
        btnUpdateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirlinerActionPerformed(evt);
            }
        });
        add(btnUpdateAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 40));

        btnCreateAirliner.setText("Create New Airliner");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });
        add(btnCreateAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 210, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH AIRLINER RESULT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 350, 38));

        tblsearchairliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airliner Name", "Airliner Address", "Number of Aircrafts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblsearchairliners);
        if (tblsearchairliners.getColumnModel().getColumnCount() > 0) {
            tblsearchairliners.getColumnModel().getColumn(0).setResizable(false);
            tblsearchairliners.getColumnModel().getColumn(1).setResizable(false);
            tblsearchairliners.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 600, 150));

        btnManageFlights.setText("Select and Manage Flights");
        btnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightsActionPerformed(evt);
            }
        });
        add(btnManageFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 210, 40));

        btnDeleteAirliner.setText("Delete Airliner");
        btnDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlinerActionPerformed(evt);
            }
        });
        add(btnDeleteAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAirlinerActionPerformed
        // TODO add your handling code here:        
        Airliner result = travelagency.getAirlinerdirectory().searchAirliner(txtsearchairlines.getText()); 
        String r = String.valueOf(result);
        if(result == null) {
               JOptionPane.showMessageDialog(null, "Account number you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
  
        }
        else {
            DefaultTableModel dtm = (DefaultTableModel) tblsearchairliners.getModel();
                  dtm.setRowCount(0);
          for (int i=0;i<travelagency.getAirlinerdirectory().getAirlinerList().size();i++){
             if((travelagency.getAirlinerdirectory().getAirlinerList().get(i).getAirlinername()).equals(r)) {
                   for(Airliner airliner: travelagency.getAirlinerdirectory().getAirlinerList()) {
                     Object[] row = new Object[4];
                     row[0]=airliner.getAirlinername();
                     row[1]=airliner.getAirlineraddress();
                     row[2]=airliner.getNoofairlines();
                     dtm.addRow(row);
                     break;
                  
                     }   
        
                }
            }
    }//GEN-LAST:event_btnSearchAirlinerActionPerformed
    }
    private void btnUpdateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblmanageairliners.getSelectedRow();
         if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);

         }
         else {
           Airliner airliner = (Airliner)tblmanageairliners.getValueAt(selectedRow, 0);
           ViewAirlinerJPanel panel = new ViewAirlinerJPanel(UserProcessContainer, airliner);
           UserProcessContainer .add("ViewAirlinerJPanelanel",panel);
           CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
           layout.next(UserProcessContainer);
         }
    }//GEN-LAST:event_btnUpdateAirlinerActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
       CreateAirlinerJPanel panel = new CreateAirlinerJPanel(UserProcessContainer,travelagency.getAirlinerdirectory());
        UserProcessContainer.add("CreateAirlinerJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer); 
        
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightsActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblmanageairliners.getSelectedRow();
         if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);

         }
         else {
           Airliner airliner = (Airliner)tblmanageairliners.getValueAt(selectedRow, 0);
           ManageFlightJPanel panel = new ManageFlightJPanel(UserProcessContainer,airliner);
           UserProcessContainer.add("ManageFlightManageJPanelanel",panel);
           CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
           layout.next(UserProcessContainer);
         }
    }//GEN-LAST:event_btnManageFlightsActionPerformed

    private void btnDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlinerActionPerformed
        // TODO add your handling code here:
           int selectedRow = tblmanageairliners.getSelectedRow();
        if(selectedRow  >= 0) {
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the airliner details ?","Warning",dialogButton);
           if(dialogResult == JOptionPane.YES_OPTION) {
               Airliner airliner = (Airliner) tblmanageairliners.getValueAt(selectedRow,0);
               travelagency.getAirlinerdirectory().deleteAirliner(airliner);
               populateTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnDeleteAirliner;
    private javax.swing.JButton btnManageFlights;
    private javax.swing.JButton btnSearchAirliner;
    private javax.swing.JButton btnUpdateAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblmanageairliners;
    private javax.swing.JTable tblsearchairliners;
    private javax.swing.JTextField txtsearchairlines;
    // End of variables declaration//GEN-END:variables
}
