/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRAdmin;

import Business.Business;
import Business.Person;
import Business.UserAccount;
import UserInterface.SystemAdmin.ManageUserAccountDirectoryJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class DisplayHRAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayHRAdminJPanel
     */
    private Business business;
    private JPanel UserProcessContainer;
    private UserAccount useraccount;
   

    public DisplayHRAdminJPanel(JPanel UserProcessContainer, Business business, UserAccount useraccount) {
        initComponents();
        this.business = business;
        this.UserProcessContainer = UserProcessContainer;
        this.useraccount = useraccount;
        
        
        lblUsername.setText(useraccount.getUsername());
        lblRole.setText(useraccount.getRole());
        lblStatus.setText(useraccount.getAccountstatus());
    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRole = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnManageuseraccounts = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("UserName         = ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Account Status  =");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Role                    =");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 40));

        lblUsername.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 40));

        btnManageuseraccounts.setText("Manage User Accounts >");
        btnManageuseraccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageuseraccountsActionPerformed(evt);
            }
        });
        add(btnManageuseraccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 360, 40));

        lblStatus.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageuseraccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageuseraccountsActionPerformed
        // TODO add your handling code here:
        ManagePersonDirectoryJPanel panel = new ManagePersonDirectoryJPanel(UserProcessContainer,business);
        UserProcessContainer.add("ManagePersonDirectoryJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnManageuseraccountsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageuseraccounts;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
