/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRAdmin;

import Business.Business;
import Business.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class FindPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindPersonJPanel
     */
    private JPanel UserProcessContainer;
    private Business business;
    private Person person;

    FindPersonJPanel(JPanel UserProcessContainer, Business business) {
         initComponents();
         this.UserProcessContainer = UserProcessContainer;
         this.business = business;
         populateTable();
    }
    
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
        dtm.setRowCount(0);
        for(Person person: business.getPersondirectory().getPersonlist()) {
            Object[] row = new Object[3];
            row[0]=person;
            row[1]=person.getLastName();
            row[2]=person.getSSN();
            
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFindByFirstName = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FIND PERSON");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 310, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Find By FirstName :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 40));
        add(txtFindByFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 230, 50));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 250, 40));

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
         Person result = business.getPersondirectory().searchPerson(txtFindByFirstName.getText());
        String r = String.valueOf(result);
        if(result == null) {
               JOptionPane.showMessageDialog(null, "Username you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
  
        }
        else {
            DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
                  dtm.setRowCount(0);
            for(Person person:business.getPersondirectory().getPersonlist()){
                if(person.getFirstName().equals(r)) {
                    Object[] row = new Object[3];
                    row[0]=person;
                    row[1]=person.getLastName();
                    row[2]=person.getSSN();
                    
                    dtm.addRow(row);
                    break;
                }
                
            }  
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JTextField txtFindByFirstName;
    // End of variables declaration//GEN-END:variables
}
