/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRAdmin;

import Business.Business;
import Business.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ManagePersonDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePersonDirectoryJPanel
     */
   private JPanel UserProcessContainer;
   private Business business;
   private Person  person;

    ManagePersonDirectoryJPanel(JPanel UserProcessContainer, Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        populateTable();
    }
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) tblPersonList.getModel();
        dtm.setRowCount(0);
        for(Person person: business.getPersondirectory().getPersonlist()) {
            Object[] row = new Object[3];
            row[0]=person;
            row[1]=person.getLastName();
            row[2]=person.getSSN();
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonList = new javax.swing.JTable();
        btnFindPerson = new javax.swing.JButton();
        btnNewPerson = new javax.swing.JButton();
        btnUpdatePerson = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Person List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 40));

        tblPersonList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPersonList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 240));

        btnFindPerson.setText("Find Person >>");
        btnFindPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPersonActionPerformed(evt);
            }
        });
        add(btnFindPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 360, 40));

        btnNewPerson.setText("New Person >>");
        btnNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPersonActionPerformed(evt);
            }
        });
        add(btnNewPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 360, 40));

        btnUpdatePerson.setText("Update Person >>");
        btnUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonActionPerformed(evt);
            }
        });
        add(btnUpdatePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 360, 40));

        btnDelete.setText("Delete Person");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPersonActionPerformed
        // TODO add your handling code here:
        FindPersonJPanel panel = new FindPersonJPanel(UserProcessContainer,business);
        UserProcessContainer.add("ManagePersonDirectoryJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
       
    }//GEN-LAST:event_btnFindPersonActionPerformed

    private void btnNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPersonActionPerformed
        // TODO add your handling code here:
        NewPersonJPanel panel = new NewPersonJPanel(UserProcessContainer,business);
        UserProcessContainer.add("ManagePersonDirectoryJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnNewPersonActionPerformed

    private void btnUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPersonList.getSelectedRow();
        if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table to view details","Warning",JOptionPane.WARNING_MESSAGE);

        }
        else {
        Person person =(Person)tblPersonList.getValueAt(selectedRow,0);
        UpdatePersonJPanel panel = new UpdatePersonJPanel(UserProcessContainer,person);
        UserProcessContainer.add("UpdatePersonJPanel",panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
        }
    }//GEN-LAST:event_btnUpdatePersonActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
              int selectedRow = tblPersonList.getSelectedRow();
        if(selectedRow  >= 0) {
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the person details ?","Warning",dialogButton);
           if(dialogResult == JOptionPane.YES_OPTION) {
               Person person = (Person) tblPersonList.getValueAt(selectedRow,0);
               business.getPersondirectory().deletePerson(person);
               populateTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindPerson;
    private javax.swing.JButton btnNewPerson;
    private javax.swing.JButton btnUpdatePerson;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonList;
    // End of variables declaration//GEN-END:variables
}
