/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRAdmin;

import Business.Business;
import Business.Person;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class UpdatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonJPanel
     */
    private JPanel UserProcessContainer;
    private Person person;

    UpdatePersonJPanel(JPanel UserProcessContainer, Person person) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.person = person;
        System.out.println("FN"+ person.getFirstName());
        populatePersonDetails(); 
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    
           
                    
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE PERSON");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, 30));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("First Name : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, 30));

        txtFirstName.setEnabled(false);
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 230, 40));

        txtLastName.setEnabled(false);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 230, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Last Name :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 30));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 230, 50));

        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 230, 50));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("SSN :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, 40));

        txtSSN.setEnabled(false);
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer .remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        ManagePersonDirectoryJPanel managepersondirectoryjpanel = (ManagePersonDirectoryJPanel) component;
        managepersondirectoryjpanel.populateTable();
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSN.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       if((txtFirstName.getText() != null)&& !(txtFirstName.getText().isEmpty())
           && (txtLastName.getText() != null)&& !(txtLastName.getText().isEmpty()) 
           && (txtSSN.getText() != null)&& !(txtSSN.getText().isEmpty())
           
            )
        {
         try {    
        
        String firstname = txtFirstName.getText();
        String lastname = txtLastName.getText();
        String ssn = txtSSN.getText();
        
        Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtFirstName.getText() + txtLastName.getText() + txtSSN.getText() );
            boolean boo = m.find();
            if(boo == true || firstname == null || lastname == null || ssn == null) {
            JOptionPane.showMessageDialog(null,"Please remove special character");
        }
            
        person.setFirstName(firstname);
        person.setLastName(lastname);
        person.setSSN(Integer.parseInt(ssn));
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

        JOptionPane.showMessageDialog(null,"Person successfully updated");
         }
    catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Data in SSN ");
        }
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }       
    }//GEN-LAST:event_btnSaveActionPerformed
    private void populatePersonDetails() {
        txtFirstName.setText(String.valueOf(person));
        txtLastName.setText(person.getLastName());
        txtSSN.setText(String.valueOf(person.getSSN()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
