/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.ProviderRole;

import UserInterface.Inventory.ClinicRole.*;
import UserInterface.Inventory.*;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ManageVaccinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccinesJPanel
     */
   JPanel userProcessContainer;
   Enterprise enterprise;
   Organization organization;
   

    ManageVaccinesJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization) {
     initComponents();
     this.userProcessContainer = userProcessContainer;
     this.enterprise = enterprise;
     this.organization = organization;
     lblEnterprise.setText(enterprise.getName());
     populateTable();
    }
public void populateTable(){
     DefaultTableModel model = (DefaultTableModel) tblManageVaccine.getModel();

        model.setRowCount(0);

        for (Vaccine vaccine : organization.getVaccineDirectory().getVaccineList()) {
                Object row[] = new Object[3];
                row[0] = vaccine;
                row[1] = vaccine.getDiseaseName();
                row[2] = vaccine.getVaccineqty();
                ((DefaultTableModel) tblManageVaccine.getModel()).addRow(row);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageVaccine = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVaccine = new javax.swing.JTextField();
        txtDisease = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtvaccineqty = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE VACCINES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 220, 40));

        lblEnterprise.setText("<value>");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Enterprise :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        tblManageVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Disease", "Vaccine", "VaccineQty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageVaccine);
        if (tblManageVaccine.getColumnModel().getColumnCount() > 0) {
            tblManageVaccine.getColumnModel().getColumn(0).setResizable(false);
            tblManageVaccine.getColumnModel().getColumn(1).setResizable(false);
            tblManageVaccine.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 140));

        jLabel3.setText("Vaccine Quantity");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 140, 40));

        jLabel4.setText("Disease");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 140, 40));
        add(txtVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 140, 30));
        add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 140, 30));

        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 220, 50));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 40));

        jLabel5.setText("Vaccine");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 140, 40));
        add(txtvaccineqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
         String disease = txtDisease.getText();
        String vaccine = txtVaccine.getText();
        String vaccineqty = txtvaccineqty.getText();
        if((disease != null)&& !(disease.isEmpty())
           && (vaccine != null)&& !(vaccine.isEmpty()) 
           && (vaccineqty != null)&& !(vaccineqty.isEmpty())
           
            )
        {
            
          try {
            Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(disease + vaccine + vaccineqty);
            boolean boo = m.find();
            if(boo == true || disease == null || vaccine == null || vaccineqty == null) {
            JOptionPane.showMessageDialog(null,"Please remove special character");
        }
            else{
                
                organization.getVaccineDirectory().addVaccine(vaccine, disease,Integer.parseInt(vaccineqty));
                 populateTable();
            JOptionPane.showMessageDialog(null,"Person successfully added");
            }
          }catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Data in SSN ");
        }
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }
    }//GEN-LAST:event_btnEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblManageVaccine;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtVaccine;
    private javax.swing.JTextField txtvaccineqty;
    // End of variables declaration//GEN-END:variables
}
