/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Administrator;

import Business.Business;
import Business.EmployeeDirectory;
import Business.MarketList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author runhzx
 */
public class AdministratorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdministratorJPanel
     */
    
    private JPanel userProcessContainer;
    private Business business;
    private EmployeeDirectory employeedirectory;
    private MarketList marketlist;
    public AdministratorJPanel(JPanel userProcessContainer, Business business) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.business = business;
    this.employeedirectory = business.getEmployeedirectory();
    this.marketlist = business.getMarketlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSalesperson = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Administrator");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 6, -1, -1));

        btnSalesperson.setText("Salesperson   >>");
        btnSalesperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalespersonActionPerformed(evt);
            }
        });
        add(btnSalesperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 247, 153, -1));

        btnCustomer.setText("Customer       >>");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 319, -1, -1));

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 489, 150, 50));

        btnAnalysis.setText("Analysis>>");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });
        add(btnAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalespersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalespersonActionPerformed
        // TODO add your handling code here:
        SalespersonJPanel sp = new SalespersonJPanel(userProcessContainer,employeedirectory);
        userProcessContainer.add("Salesperson", sp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSalespersonActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        CustomerJPanel up = new CustomerJPanel(userProcessContainer,marketlist);
        userProcessContainer.add("Customer", up);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
       AnalysisJPanel ap = new AnalysisJPanel(userProcessContainer,business);
        userProcessContainer.add("Analysis", ap);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnSalesperson;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
