/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Administrator;

import Business.Customer;
import Business.Market;
import Business.MarketList;
import Business.SalesPerson;
import UserInterface.Supplier.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class CreateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateSupplier
     */
    private JPanel userProcessContainer;
    private MarketList marketlist;
    CreateCustomerJPanel(JPanel userProcessContainer, MarketList marketList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.marketlist = marketList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerID = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerMarketType = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Create Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Customer Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Customer ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 100, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 170, -1));

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 170, -1));
        add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 170, -1));

        btnCreateCustomer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnCreateCustomer.setText("Create");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });
        add(btnCreateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Market Type:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));
        add(txtCustomerMarketType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        CustomerJPanel cjp = (CustomerJPanel) component;
        cjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:
          if(txtCustomerName.getText().equals("") || txtCustomerID.getText().equals("") || txtCustomerMarketType.getText().equals("")|| txtCustomerEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please input all the content");
        }else{
           String cname = txtCustomerName.getText();
            String cid = txtCustomerID.getText();
            String cemail = txtCustomerEmail.getText();
            String cmtype = txtCustomerMarketType.getText();
            Market market= marketlist.addMarket();
            market.getCustomer().setCustomerName(cname);
            market.getCustomer().setCustomerId(Integer.parseInt(cid));
            market.getCustomer().setEmailAddress(cemail);
            market.setMarketType(cmtype);
             JOptionPane.showMessageDialog(null,"Customer created successufully");
        }
    }//GEN-LAST:event_btnCreateCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerMarketType;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
