/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import Business.Business;
import Business.Product;
import Business.Supplier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class BrowseProductCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrowseProductCatalogJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    BrowseProductCatalogJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        comboboxSupplier.removeAllItems();
        for(int i=0;i<business.getSuplierdirectory().getSupplierlist().size();i++){
        comboboxSupplier.addItem(business.getSuplierdirectory().getSupplierlist().get(i).getSupplierName());
        }
        
        populateTable111();
    }

    public void populateTable111() {
        DefaultTableModel dtm = (DefaultTableModel)tblProduct.getModel();
        dtm.setRowCount(0);
        System.out.println("QQQQQQ");
        System.out.println(business.getSuplierdirectory().getSupplierlist());
        for(Supplier supplier: business.getSuplierdirectory().getSupplierlist()){
            System.out.println("SUpplierfor");
            for(Product product: supplier.getProductcatalog().getProductlist()){
                System.out.println("12323444HELLO"+ product.getProductName());
            Object [] row = new Object[4];
            
           row[0]=product.getProductId();
           row[1]= product.getProductDescription();
           row[2]=product.getProductQuantity();
           row[3]=product;
            dtm.addRow(row);
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblSalesPersonName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboboxSupplier = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("SALES CONSOLE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 40));

        lblSalesPersonName.setText("SALES PERSON NAME");
        add(lblSalesPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 170, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Supplier");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 40));

        comboboxSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboboxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 40));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 40));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Product Description", "Product Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 780, 200));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         Supplier result =business.getSuplierdirectory().searchSupplier(String.valueOf(comboboxSupplier.getSelectedItem()));
        String r = String.valueOf(comboboxSupplier.getSelectedItem());
        if(result == null) {
               JOptionPane.showMessageDialog(null, "U you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
  
        }
        else {
               DefaultTableModel dtm = (DefaultTableModel)tblProduct.getModel();
        dtm.setRowCount(0);
        System.out.println("QQQQQQ");
        System.out.println(business.getSuplierdirectory().getSupplierlist());
        for(Supplier supplier: business.getSuplierdirectory().getSupplierlist()){
            System.out.println("SUpplierfor");
            for(Product product: supplier.getProductcatalog().getProductlist()){
            if(supplier.getSupplierName().equals(r)){
                System.out.println("12323444HELLO"+ product.getProductName());
            Object [] row = new Object[4];
            
           row[0]=product.getProductId();
           row[1]= product.getProductName();
           row[2]=product.getProductDescription();
           row[3]=product.getProductQuantity();
            dtm.addRow(row);
        }
        
            }}
        }
            
            
            
            
            
         
            
            
            
            
            
            
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboboxSupplier;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSalesPersonName;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
