/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import Business.Business;
import Business.Customer;
import Business.Market;
import Business.OrderList;
import Business.SalesPerson;
import Business.Supplier;
import UserInterface.Supplier.ManageProductCatalogJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private SalesPerson salesperson;
   double tcomission = 0.0;
    int totalquantity = 0;
    double totalorderprice =0.0;
    ManageCustomerJPanel(JPanel userProcessContainer, Business business, SalesPerson salesperson) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.salesperson = salesperson;
        lblSalesPersonName.setText(salesperson.getSalesPersonName());
        populateTable12();
        populateTable3();
        
    }
    
    public void populateTable3() {
       // int rowcount = tblSupplier.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)tblcustomersales.getModel();
        dtm.setRowCount(0);
        for(Market market:business.getMarketlist().getMarketList()){
            Object [] row = new Object[4];
            row[0]=market.getCustomer().getCustomerId();
            row[1]=market.getCustomer().getCustomerName();
            row[2]=market.getCustomer().getEmailAddress();
            row[3]=market;
            dtm.addRow(row);
        }
    } 

    public void populateTable12() {
      
     
      for(OrderList orderlist:salesperson.getOrderlistcatalog().getOrCatalog()){
      Object [] row = new Object[6];
   
      tcomission = tcomission + orderlist.getSalespersoncomission();
      totalquantity = totalquantity + orderlist.getTotalorderlistquantity();
     totalorderprice = totalorderprice + orderlist.getOrdertotalprice();
      
    } 
       salesperson.getOrderlistcatalog().setTotalquantitypersalesperson(totalquantity);
      salesperson.getOrderlistcatalog().setTotalcommision(tcomission);
      salesperson.getOrderlistcatalog().setTotalorderlistcsatalogprice(totalorderprice);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalesPersonName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        btnReviewSalesCommission = new javax.swing.JButton();
        btnServerCustomer = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnReviewSalesOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomersales = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lblSalesPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 170, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Customer Id :");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("SALES CONSOLE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));

        txtCustomerId.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, 40));

        btnReviewSalesCommission.setText("Review Sales Commission");
        btnReviewSalesCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewSalesCommissionActionPerformed(evt);
            }
        });
        add(btnReviewSalesCommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 190, 50));

        btnServerCustomer.setText("Server Customer");
        btnServerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerCustomerActionPerformed(evt);
            }
        });
        add(btnServerCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 50));

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 190, 50));

        btnReviewSalesOrder.setText("Review Sales Order");
        btnReviewSalesOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewSalesOrderActionPerformed(evt);
            }
        });
        add(btnReviewSalesOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 190, 50));

        tblcustomersales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Id", "Customer Name", "Customer email", "MarketType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcustomersales);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 190));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 49, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnServerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerCustomerActionPerformed
        // TODO add your handling code here:
     int selectedRow =tblcustomersales.getSelectedRow();
         if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);

         }
         else {
           Market market = (Market)tblcustomersales.getValueAt(selectedRow, 3);
          // System.out.println("12344"+supplier);
     //  ServerCustomerJPanel scj= new ServerCustomerJPanel(userProcessContainer,market,business);
            ServerCustomerJPanel scj= new ServerCustomerJPanel(userProcessContainer,business,market,salesperson);  
     userProcessContainer.add("ManageProductCatalog", scj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
         }
    }//GEN-LAST:event_btnServerCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReviewSalesOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewSalesOrderActionPerformed
        // TODO add your handling code here:
        ReviewSalesOrderJPanel rso = new ReviewSalesOrderJPanel(userProcessContainer,salesperson,business);
        userProcessContainer.add("ReviewSalesOrder",rso);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewSalesOrderActionPerformed

    private void btnReviewSalesCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewSalesCommissionActionPerformed
        // TODO add your handling code here:
        ReviewSalesComissionJPanel rsc = new ReviewSalesComissionJPanel(userProcessContainer,business,salesperson);
        userProcessContainer.add("ReviewSalesComission",rsc);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewSalesCommissionActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
              Market result = business.getMarketlist().searchMarket(Integer.parseInt(txtCustomerId.getText()));
        int r = Integer.parseInt(txtCustomerId.getText());

        if(result == null) {
               JOptionPane.showMessageDialog(null, "CustomerId you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
  
        }
        else {
            DefaultTableModel dtm = (DefaultTableModel) tblcustomersales.getModel();
                  dtm.setRowCount(0);
            for(Market market:business.getMarketlist().getMarketList()){
                if(market.getCustomer().getCustomerId() == r) {
                    Object[] row = new Object[4];
                    row[0]=market.getCustomer().getCustomerId();
                    row[1]=market.getCustomer().getCustomerName();
                    row[2]=market.getCustomer().getEmailAddress();
                    row[3]= market;
                    dtm.addRow(row);
                    break;
                }
                
            }  
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReviewSalesCommission;
    private javax.swing.JButton btnReviewSalesOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnServerCustomer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSalesPersonName;
    private javax.swing.JTable tblcustomersales;
    private javax.swing.JTextField txtCustomerId;
    // End of variables declaration//GEN-END:variables
}
