/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import Business.Business;
import Business.Market;
import Business.Order;
import Business.OrderList;
import Business.SalesPerson;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ReviewSalesOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewSalesOrderJPanel
     */
    private JPanel userProcessContainer;
    private SalesPerson salesperson;
    private Business business;
    ReviewSalesOrderJPanel(JPanel userProcessContainer, SalesPerson salesperson,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salesperson = salesperson;
        this.business = business;
        lblSalesPersonName.setText(salesperson.getSalesPersonName());
        populateTable();
    }
public void populateTable() {
       // int rowcount = tblSupplier.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)tblview.getModel();
        dtm.setRowCount(0);
      //  for(OrderList orderlist:salesperson.getOrderlistcatalog().getSalesPersonOrder()){
   //   for(Order order:salesperson.getOrderListSalesPerson().getOrderList()){  
  // for(OrderList orderlist:salesperson.getOrderlistcatalog().getOrCatalog()){
 // for(SalesPerson salesperson:business.getEmployeedirectory().getSalesPersonList()){
      for(OrderList orderlist:salesperson.getOrderlistcatalog().getOrCatalog()){
      Object [] row = new Object[2];
      //row[0]=market.getCustomer().getCustomerId();
     // row[1]= market.getCustomer().getCustomerName();
      row[0]=orderlist;
      row[1]=orderlist.getOrdertotalprice();
  //          row[0]=order;
    //        row[1]=order.getAmountprice();
            
            dtm.addRow(row);
     //   }
      }
  //  } 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblSalesPersonName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblview = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("SALES CONSOLE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));

        lblSalesPersonName.setText("SALES PERSON NAME");
        add(lblSalesPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 170, 40));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 210, 50));

        tblview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "OrderList No", "OrderList Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblview);
        if (tblview.getColumnModel().getColumnCount() > 0) {
            tblview.getColumnModel().getColumn(0).setResizable(false);
            tblview.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 780, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSalesPersonName;
    private javax.swing.JTable tblview;
    // End of variables declaration//GEN-END:variables
}
