/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import Business.Business;
import Business.Market;
import Business.MarketList;
import Business.SalesPerson;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class ServerCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServerCustomerJPanel
     */
    private JPanel userProcessContainer;
    private Market market;
   // private MarketList marketList;
    private Business business;
    private SalesPerson salesperson;
    //ServerCustomerJPanel(JPanel userProcessContainer, Market market,Business business) {

    ServerCustomerJPanel(JPanel userProcessContainer, Business business,Market market, SalesPerson salesPerson) {
    initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
       this.market = market;
       this.salesperson = salesPerson;
       lblSalesPersonName.setText(salesPerson.getSalesPersonName());
        lblcid.setText(String.valueOf(market.getCustomer().getCustomerId()));
        lblcname.setText(market.getCustomer().getCustomerName());
        lblcemail.setText(market.getCustomer().getEmailAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblSalesPersonName = new javax.swing.JLabel();
        btnViewCustomerHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnBookCustomerOrder = new javax.swing.JButton();
        btnBrowseProductCatalog = new javax.swing.JButton();
        lblcemail = new javax.swing.JLabel();
        lblcid = new javax.swing.JLabel();
        lblcname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("SALES CONSOLE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));
        add(lblSalesPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 170, 40));

        btnViewCustomerHistory.setText("View Customer History");
        btnViewCustomerHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerHistoryActionPerformed(evt);
            }
        });
        add(btnViewCustomerHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 210, 50));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 50));

        btnBookCustomerOrder.setText("Book Customer Order");
        btnBookCustomerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookCustomerOrderActionPerformed(evt);
            }
        });
        add(btnBookCustomerOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 50));

        btnBrowseProductCatalog.setText("Browse Product Catalog");
        btnBrowseProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProductCatalogActionPerformed(evt);
            }
        });
        add(btnBrowseProductCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 330, 50));
        add(lblcemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 170, 30));
        add(lblcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 30));
        add(lblcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 30));

        jLabel1.setText("Customer Details :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookCustomerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookCustomerOrderActionPerformed
        // TODO add your handling code here:
        BookCustomerOrderJPanel bco = new BookCustomerOrderJPanel(userProcessContainer,business,salesperson,market);
        userProcessContainer.add("BookCustomerOrder",bco);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBookCustomerOrderActionPerformed

    private void btnViewCustomerHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerHistoryActionPerformed
        // TODO add your handling code here:
        ViewCustomerHistoryJPanel vch = new ViewCustomerHistoryJPanel(userProcessContainer,market,salesperson);
        userProcessContainer.add("ViewCustomerHistory",vch);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewCustomerHistoryActionPerformed

    private void btnBrowseProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductCatalogActionPerformed
        // TODO add your handling code here:
        BrowseProductCatalogJPanel bpc = new BrowseProductCatalogJPanel(userProcessContainer,business);
        userProcessContainer.add("BrowseProductCatalog",bpc);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBrowseProductCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookCustomerOrder;
    private javax.swing.JButton btnBrowseProductCatalog;
    private javax.swing.JButton btnViewCustomerHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblSalesPersonName;
    private javax.swing.JLabel lblcemail;
    private javax.swing.JLabel lblcid;
    private javax.swing.JLabel lblcname;
    // End of variables declaration//GEN-END:variables
}
