/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Catalog.Airline;
import Catalog.History;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author rishabhjain
 */
public class CreateJPanel extends javax.swing.JPanel {
   
    /**
     * Creates new form CreateJPanel
     */
  // public static String dateS =  null;
   private History ah1;
   public CreateJPanel(History ah1) {
          initComponents();
          this.ah1= ah1;
          
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSrno = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblManyr = new javax.swing.JLabel();
        lblMaincerti = new javax.swing.JLabel();
        lblModelno = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtMainCerti = new javax.swing.JTextField();
        txtManuyear = new javax.swing.JTextField();
        txtSrno = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        lblMadeby = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtModelno = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtMadeby = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        lblduration = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtAvail = new javax.swing.JTextField();
        lblAirline = new javax.swing.JLabel();
        txtAirline = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("CREATE RECORD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 6, 184, 39));

        lblSrno.setText("Sr No.");
        add(lblSrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 51, 171, 29));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 86, 171, 29));

        lblTime.setText("Time");
        add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 121, 171, 29));

        lblManyr.setText("Manufacturing Year");
        add(lblManyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 191, 175, 29));

        lblMaincerti.setText("Maintenance Certificate");
        add(lblMaincerti, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 156, 175, 29));

        lblModelno.setText("Model No.");
        add(lblModelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 51, 83, 29));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 87, 133, -1));
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 122, 133, -1));
        add(txtMainCerti, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 157, 133, -1));
        add(txtManuyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 192, 133, -1));
        add(txtSrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 52, 133, -1));

        lblSeats.setText("Seats");
        add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 86, 83, 29));

        lblMadeby.setText("Made By");
        add(lblMadeby, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 121, 83, 29));

        lblFrom.setText("From");
        add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 156, 83, 29));

        lblTo.setText("To");
        add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 191, 83, 29));
        add(txtModelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 52, 133, -1));
        add(txtSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 87, 133, -1));
        add(txtMadeby, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 122, 133, -1));
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 192, 133, -1));
        add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 157, 133, -1));

        lblduration.setText("Duration");
        add(lblduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 226, 175, 29));

        lblAvailability.setText("Availability");
        add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 226, 83, 29));
        add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 227, 133, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 353, -1, -1));
        add(txtAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 227, 133, -1));

        lblAirline.setText("Airline");
        add(lblAirline, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 261, 83, 29));
        add(txtAirline, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 262, 133, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(!txtSrno.getText().equals("") && !txtDate.getText().equals("") && !txtTime.getText().equals("") && !txtMainCerti.getText().equals("")
            && !txtManuyear.getText().equals("") && !txtDuration.getText().equals("") && !txtModelno.getText().equals("") && !txtSeats.getText().equals("")
                && !txtMadeby.getText().equals("") && !txtFrom.getText().equals("") && !txtTo.getText().equals("") && !txtAvail.getText().equals("") )
        {
        String srno = txtSrno.getText();
        String date =txtDate.getText();
        String time =txtTime.getText();
        String maincerti =txtMainCerti.getText();
        int manuyr =Integer.parseInt(txtManuyear.getText());
        int duration =Integer.parseInt(txtDuration.getText());
        int modelno =Integer.parseInt(txtModelno.getText());
        int    seats = Integer.parseInt(txtSeats.getText());
        String madeby =txtMadeby.getText();
        String from = txtFrom.getText();
        String to = txtTo.getText();
        int avail = Integer.parseInt(txtAvail.getText());
        String air = txtAirline.getText();
        
        Airline a = ah1.addAirline1();
        a.setSrNo(srno);
        a.setDate(date);
        a.setTime(time);
        a.setMadeBy(madeby);
        a.setManYr(manuyr);
        a.setModelNo(modelno);
        a.setSeats(seats);
        a.setMainCerti(maincerti);
        a.setFrom(from);
        a.setTo(to);
        a.setDuration(duration);
        a.setAvail(avail);
        a.setAirline(air);
        JOptionPane.showMessageDialog(null,"Record Added Successfully");
  
        txtSrno.setText("");
        txtDate.setText("");
        txtTime.setText("");
        txtMainCerti.setText("");
        txtManuyear.setText("");
        txtDuration.setText("");
        txtModelno.setText("");
        txtSeats.setText("");
        txtMadeby.setText("");
        txtFrom.setText("");
        txtTo.setText("");
        txtAvail.setText("");
        txtAirline.setText("");
        }
        else
            JOptionPane.showMessageDialog(null,"Enter the Details");
       
    }//GEN-LAST:event_btnCreateActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAirline;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblMadeby;
    private javax.swing.JLabel lblMaincerti;
    private javax.swing.JLabel lblManyr;
    private javax.swing.JLabel lblModelno;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSrno;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblduration;
    private javax.swing.JTextField txtAirline;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtMadeby;
    private javax.swing.JTextField txtMainCerti;
    private javax.swing.JTextField txtManuyear;
    private javax.swing.JTextField txtModelno;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSrno;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
