/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Person;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class FindUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindUserAccountJPanel
     */
    public FindUserAccountJPanel() {
        
    }
    private JPanel UserProcessContainer;
    private Business business;
    FindUserAccountJPanel(JPanel UserProcessContainer, Business business) {
    initComponents();
    this.UserProcessContainer=UserProcessContainer;
    this.business=business;
    populateTable();
    }
    
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<business.getPersondirectory().getPersonlist().size();i++) {
            for(UserAccount useraccount: business.getPersondirectory().getPersonlist().get(i).getListofuseraccount()) {
            Object[] row = new Object[7];
            row[0]=useraccount;
            row[1]=business.getPersondirectory().getPersonlist().get(i).getFirstName();
            row[2]=business.getPersondirectory().getPersonlist().get(i).getLastName();
            row[3]=useraccount.getPassword();
            row[4]= useraccount.getRole();
            row[5]=useraccount.getAccountstatus();
            row[6]=business.getPersondirectory().getPersonlist().get(i).getSSN();
            
            
            dtm.addRow(row);
            }
        }
        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFindByFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtFindByFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 230, 50));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FIND USER ACCOUNT");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 310, 40));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 250, 40));

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User Name", "FirstName", "LastName", "Password", "Account role", "Account Status", "SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 650, 240));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Find By FirstName :");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 40));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
          Person result = business.getPersondirectory().searchPerson(txtFindByFirstName.getText());
        String r = String.valueOf(result);
        if(result == null) {
               JOptionPane.showMessageDialog(null, "Username you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
  
        }
        else {
            DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
            dtm.setRowCount(0);
                  
            for(int i=0;i<business.getPersondirectory().getPersonlist().size();i++) {
            for(UserAccount useraccount: business.getPersondirectory().getPersonlist().get(i).getListofuseraccount()) {
            if(business.getPersondirectory().getPersonlist().get(i).getFirstName().equals(r)) { 
            Object[] row = new Object[7];
            row[0]=useraccount;
            //CHECK IT BEFORE PROCEEDING TO FINAL STEP
            row[1]=business.getPersondirectory().getPersonlist().get(i).getFirstName();
            row[2]=business.getPersondirectory().getPersonlist().get(i).getLastName();
            //
            row[3]=useraccount.getPassword();
            row[4]= useraccount.getRole();
            row[5]=useraccount.getAccountstatus();
            row[6]=business.getPersondirectory().getPersonlist().get(i).getSSN();
            dtm.addRow(row);
            }
        }
        }
           
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JTextField txtFindByFirstName;
    // End of variables declaration//GEN-END:variables
}
