/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Person;
import Business.UserAccount;
import UserInterface.HRAdmin.ManagePersonDirectoryJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class UpdateUserAccountStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUserAccountStatus
     */
    private JPanel UserProcessContainer;
    private Business business;
    private Person person;
    private UserAccount useraccount;
    UpdateUserAccountStatusJPanel(JPanel UserProcessContainer, UserAccount useraccount) {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(radiobtnActive);
        group.add(radiobtnDisabled);
        comboboxRole.removeAllItems();
        comboboxRole.addItem("SystemAdmin");
        comboboxRole.addItem("HRAdmin");
        comboboxRole.addItem("Student");
        this.UserProcessContainer = UserProcessContainer;
        this.useraccount = useraccount;
        populatePersonDetails(); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radiobtnDisabled = new javax.swing.JRadioButton();
        radiobtnActive = new javax.swing.JRadioButton();
        comboboxRole = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update User Account");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 270, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("User Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 190, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Password :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Account Status :");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 40));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 250, 40));

        btnCancel.setText("<< BACK");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 250, 40));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 190, 50));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Role :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 40));

        radiobtnDisabled.setText("Disabled");
        add(radiobtnDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        radiobtnActive.setText("Active");
        add(radiobtnActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        comboboxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboboxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 190, 50));
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String comboRole = (String)comboboxRole.getSelectedItem();
        String username = txtUsername.getText();
        String pwd = String.valueOf(this.password.getPassword());
        if((txtUsername.getText() != null)&& !(txtUsername.getText().isEmpty())
           && (pwd != null)&& !(pwd.isEmpty()) 
            )
            {
                Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
                Matcher m = pattern.matcher(username + pwd );
                boolean boo = m.find();
                if(boo == true || username == null || pwd == null) {
                    JOptionPane.showMessageDialog(null,"Please Check your UserName/Password");
                }
            else{ 
        //
                    useraccount.setUsername(username);
                    useraccount.setPassword(pwd);
                    useraccount.setRole(comboRole);
                    if(radiobtnActive.isSelected()){
                        useraccount.setAccountstatus(radiobtnActive.getText());
                    }else{
                        useraccount.setAccountstatus(radiobtnDisabled.getText());
                    }
                    JOptionPane.showMessageDialog(null,"Person successfully updated");
                }
            }
        else{
                JOptionPane.showMessageDialog(null,"Please Enter the Data ");

            }   
       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        UserProcessContainer .remove(this);
        Component[] componentArray = UserProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        ManageUserAccountDirectoryJPanel manageuseraccountjpanel = (ManageUserAccountDirectoryJPanel) component;
        manageuseraccountjpanel.populateTable();
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboboxRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton radiobtnActive;
    private javax.swing.JRadioButton radiobtnDisabled;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
private void populatePersonDetails() {
      
        txtUsername.setText(useraccount.getUsername());
        
        password.setText(useraccount.getPassword());
    }

}
