/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Flight;
import Business.TravelAgency;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import Business.TravelAgency;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class TravelAgencyMngWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTravelAgency
     */
    private JPanel UserProcessContainer;
    private TravelAgency travelagency;
    public TravelAgencyMngWorkAreaJPanel(JPanel UserProcessContainer, TravelAgency travelagency) {
        initComponents();
        this.UserProcessContainer= UserProcessContainer;
        this.travelagency = travelagency;
        populateTable3();
    }
public void populateTable3() {
    DefaultTableModel dtm = (DefaultTableModel)tbltravelagency.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner:travelagency.getAirlinerdirectory().getAirlinerList()) {
            int i=0;
            for(Flight flight:airliner.getFlightList()) {
            
            Object[] row = new Object[7];
            row[0]=airliner.getAirlinername();
            row[1]=airliner.getFlightList().get(i).getFlightnumber();
            row[2]=airliner.getFlightList().get(i).getFrom();
            row[3]=airliner.getFlightList().get(i).getTo();
            row[4]=airliner.getFlightList().get(i).getDeparturetime();
            row[5]=airliner.getFlightList().get(i).getArrivaltime();
            row[6]=airliner.getFlightList().get(i).getFlightprice();
            dtm.addRow(row);
            i++;
                    }
        }
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltravelagency = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE TRAVEL AGENCY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Source:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Destination :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 40));
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, 40));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 159, 170, 40));

        tbltravelagency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight Number", "Source", "Destination", "Depart time", "Arrival Time", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbltravelagency);
        if (tbltravelagency.getColumnModel().getColumnCount() > 0) {
            tbltravelagency.getColumnModel().getColumn(0).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(1).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(2).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(3).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(4).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 650, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
       // ArrayList<Airliner> tempairliner = new ArrayList<>();
       if((txtSource.getText() != null)&& !(txtSource.getText().isEmpty())
           && (txtDestination.getText() != null)&& !(txtDestination.getText().isEmpty()) 
            )
       {
           
       try{
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtSource.getText() + txtDestination.getText());
            boolean boo = m.find();
        if(boo == true || source == null || destination == null ) {
            JOptionPane.showMessageDialog(null,"Please remove special character from text field");
        }
        else{
         DefaultTableModel dtm = (DefaultTableModel)tbltravelagency.getModel();
         dtm.setRowCount(0);
        for(Airliner airliner: travelagency.getAirlinerdirectory().getAirlinerList()) {
            for(Flight flight:airliner.getFlightList()) {
                if(flight.getFrom().equals(source)&&flight.getTo().equals(destination)){
                    
                  
                    Object[] row = new Object[7];
                    row[0]=airliner.getAirlinername();
                    row[1]=flight.getFlightnumber();
                    row[2]=flight.getFrom();
                    row[3]=flight.getTo();
                    row[4]=flight.getDeparturetime();
                    row[5]=flight.getArrivaltime();
                    row[6]=flight.getFlightprice();
                    System.out.println(row[1]+"/t"+row[2]);
                    dtm.addRow(row);
                   
                }
            }
        }
        }}catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Values ");
        }
       }
      else{
        JOptionPane.showMessageDialog(null,"Please Enter the Data ");

    }
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltravelagency;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
