/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.ClinicRole;

import Business.EcoSystem;
import UserInterface.Inventory.*;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class ClinicInventoryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicInventoryWorkAreaJPanel
     */
    private JPanel  userProcessContainer ;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount useraccount;
    private EcoSystem business;
    public ClinicInventoryWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account,EcoSystem business) {
    initComponents();
         this.userProcessContainer = userProcessContainer;
         this.enterprise = enterprise;
         this.organization = organization;
         this.useraccount = account;
         lblEnterprise.setText(enterprise.getName());
         this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnManageVaccines = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("INVENTORY CLINIC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 220, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Enterprise :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        lblEnterprise.setText("<value>");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        btnManageVaccines.setText("Manage Vaccines");
        btnManageVaccines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVaccinesActionPerformed(evt);
            }
        });
        add(btnManageVaccines, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 450, 40));

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 450, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageVaccinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVaccinesActionPerformed
        // TODO add your handling code here:
         ManageVaccinesJPanel manageVaccineJPanel = new ManageVaccinesJPanel(userProcessContainer, enterprise,organization);
        userProcessContainer.add("manageOrganizationJPanel", manageVaccineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageVaccinesActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ClinicOrderWorkAreaJPanel", new ClinicOrderWorkAreaJPanel(userProcessContainer,enterprise,organization,useraccount,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVaccines;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEnterprise;
    // End of variables declaration//GEN-END:variables
}
