/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.Administrator.AdministratorJPanel;
import UserInterface.SalesPerson.SalesPersonLoginJPanel;
import UserInterface.Supplier.ManageSuppliersJPanel;
import java.awt.CardLayout;
import Business.Business;
import Business.Config;
import Business.EmployeeDirectory;
import Business.Market;
import Business.MarketList;
import Business.MarketOffer;
import Business.Product;
import Business.ProductCatalog;
import Business.Supplier;
import Business.SupplierDirectory;
import UserInterface.Administrator.AdministratorLoginJPanel;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author AdministratorJPanel
 */

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    //private ProductCatalog productcatalog;
  private Business business; 
 // private Supplier supplier;
    public MainJFrame() {
        initComponents();
        //this.supplier = new Supplier();
        this.business = new Business();
         this.business = Config.Initialize();
        EmployeeDirectory ed = business.getEmployeedirectory();
        ed.displayCsv();
        MarketList ml = business.getMarketlist();
        ml.displayCsv();
       
  //  SupplierDirectory sd = business.getSuplierdirectory();
  //  sd.displayCsv();
     // ProductCatalog pc = sd.getSupplierlist().
 //       displayCsv();
    }
    /*
      public void displayCsv()
    {
        String csvFile="src/Business/SupplierDirectory.csv";
        String line =" ";
        int count = 0;
         String cvsSplitBy = ",";
         
         try(BufferedReader bf = new BufferedReader(new FileReader(csvFile))){
            while((line = bf.readLine())!=null)
             {
                // System.out.println("1111");
                count++;
                
                 String Data[] = line.split(cvsSplitBy);
                System.out.println(Data[0]);
               
                     Market market = new Market();
                     market.setMarketType(Data[9]);
                     
                     MarketOffer marketoffer = new MarketOffer();
                     marketoffer.setFloorPrice(Integer.parseInt(Data[6]));
                       marketoffer.setCeilingPrice(Integer.parseInt(Data[7]));
                         marketoffer.setActualPrice(Integer.parseInt(Data[8]));
                         
                         Product product = new Product();
                         product.setProductId(Data[3]);
                         product.setProductDescription(Data[4]); 
                         product.setProductQuantity(Integer.parseInt(Data[5]));
                         
                            
                         ProductCatalog productcatalog = new ProductCatalog();
                         productcatalog.addProduct(product);
                         
                         
                      
                         
                         
                         
                //         product.setProductId(Integer.parseInt(Data[3]));
                  //       product.setProductDescription(Data[4]);
                    //     product.setProductDescription(Data[5]);
                      //   product.setProductQuantity(Integer.parseInt(Data[6]));
                      //   product.getMarketOffer().setFloorPrice(Integer.parseInt(Data[7]));
                       //  product.getMarketOffer().setCeilingPrice(Integer.parseInt(Data[8]));
                       //  product.getMarketOffer().setActualPrice(Integer.parseInt(Data[9]));
                       //  product.getMarketOffer().getProduct().getMarketOffer().getMarket().setMarketType(Data[10]);
                       //  }       
             //    System.out.println("Hi"+supplier);
             //    System.out.println("hiii"+count +"ARRAYLIST" +supplier); 
                 }
             
        }catch (FileNotFoundException ex) {
            Logger.getLogger(ManageSuppliersJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex){
                 Logger.getLogger(ManageSuppliersJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
      // System.out.println("hiii"+count +"ARRAYLIST" +supplier);                  
    }  
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAdministrator = new javax.swing.JButton();
        btnSupplierManager = new javax.swing.JButton();
        btnSalesPerson = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setEnabled(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(180, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 600));

        btnAdministrator.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAdministrator.setText("Administrator");
        btnAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministratorActionPerformed(evt);
            }
        });

        btnSupplierManager.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSupplierManager.setText("Supplier Management");
        btnSupplierManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierManagerActionPerformed(evt);
            }
        });

        btnSalesPerson.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSalesPerson.setText("Sales Person");
        btnSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalesPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdministrator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplierManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAdministrator)
                .addGap(29, 29, 29)
                .addComponent(btnSupplierManager)
                .addGap(29, 29, 29)
                .addComponent(btnSalesPerson)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setPreferredSize(new java.awt.Dimension(600, 600));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministratorActionPerformed
        // TODO add your handling code here:
        AdministratorLoginJPanel adl = new AdministratorLoginJPanel(userProcessContainer,business);
        userProcessContainer.add("Administrator",adl);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdministratorActionPerformed

    private void btnSupplierManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierManagerActionPerformed
        // TODO add your handling code here:
        ManageSuppliersJPanel ms = new ManageSuppliersJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageSuppliers",ms);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSupplierManagerActionPerformed

    private void btnSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesPersonActionPerformed
        // TODO add your handling code here:
        SalesPersonLoginJPanel spl = new SalesPersonLoginJPanel(userProcessContainer,business);
        userProcessContainer.add("SalesPersonLogin",spl);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSalesPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrator;
    private javax.swing.JButton btnSalesPerson;
    private javax.swing.JButton btnSupplierManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
